name: PR Validation

on:
  pull_request:
    branches:
      - main
    # [default types] + [edited, review_requested]
    types: [opened, synchronize, reopened, edited, review_requested]

jobs:
  naming:
    name: PR Naming Convention Check
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '([a-z]+)\/(.+)'
          allowed_prefixes: 'release,feature,patch,major,docs,devops'
          prefix_case_sensitive: true
          min_length: 5
          max_length: 180